# Generated by Django 2.2.17 on 2020-12-20 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_remove_company_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='farRockaway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('washerName', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
